apiVersion: 1

datasources:
  - name: AirBox TimescaleDB
    type: postgres
    uid: airbox-postgres
    access: proxy
    url: db:5432
    user: ${AIRBOX_DB_USER}
    isDefault: true
    editable: false
    jsonData:
      database: ${AIRBOX_DB_NAME}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
      maxOpenConns: 5
      maxIdleConns: 2
    secureJsonData:
      password: ${AIRBOX_DB_PASSWORD}
